const {
  BASE_URL = "http://localhost",
  DATABASE_HOST = "mysql",
  DATABASE_NAME = "products",
  DATABASE_PASSWORD = "test",
  DATABASE_PORT = 3306,
  DATABASE_USERNAME = "test",
  SERVER_PORT = 3000,
} = process.env;

export {
  BASE_URL,
  DATABASE_HOST,
  DATABASE_NAME,
  DATABASE_PASSWORD,
  DATABASE_PORT,
  DATABASE_USERNAME,
  SERVER_PORT,
};
